"""Generates the wrapper files in the world0 / world-1 / world1 folders.

Iris reads a separate folder for each dimension (Overworld, Nether, End) and
wants every program (gbuffers_terrain.fsh, deferred.fsh...) as a separate file.
All of these files follow the same template: the #version line, the stage and
dimension defines, then the include of the program/*.glsl file that holds the
actual code. Instead of maintaining 174 files by hand, they are all generated
from the TABLE here.

USAGE
    python3 tools/generate_wrappers.py          writes the files
    python3 tools/generate_wrappers.py --check  only reports the differences

ADDING A NEW PROGRAM
    Add a row to the PROGRAMS table and run the tool. Example:
        ("composite3", "program/new.glsl", "330 compatibility", [], ["NEW_PASS"], None)
    If you give a program name that Iris does not support, the files are
    generated but Iris never runs them.
"""
import os, sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "shaders"))
DIMENSIONS = {"world0": "OVERWORLD", "world-1": "NETHER", "world1": "END"}
HEADER = "// Generated by tools/generate_wrappers.py - do not edit by hand.\n"

# (program name, source, #version, #extension lines {stage: [...]}, extra defines, compute info)
# compute info: None or (layout line, workGroups line, description)
V330 = "330 compatibility"
V430 = "430 compatibility"
# The VERTEX shader of the shadow pass writes to the voxel grid (imageStore). The fragment shader
# writes the hole mask (imageAtomicOr) too; it needs no extension line because the whole shadow
# program is #version 430, where image load/store is core.
IMG_EXT_VS = {"vsh": ["GL_ARB_shader_image_load_store : enable"]}
PROGRAMS = [
    # --- shadow + voxel grid ---
    ("shadow",               "program/shadow.glsl",          V430, IMG_EXT_VS, [], None),
    # --- opaque geometry (G-buffer) ---
    ("gbuffers_terrain",     "program/gbuffers_solid.glsl",  V330, {}, ["GBUFFERS_TERRAIN"], None),
    ("gbuffers_entities",    "program/gbuffers_solid.glsl",  V330, {}, ["GBUFFERS_ENTITIES"], None),
    ("gbuffers_block",       "program/gbuffers_solid.glsl",  V330, {}, ["GBUFFERS_BLOCK"], None),
    ("gbuffers_hand",        "program/gbuffers_solid.glsl",  V330, {}, ["GBUFFERS_HAND"], None),
    # --- forward-rendered ---
    ("gbuffers_basic",       "program/gbuffers_forward.glsl", V330, {}, ["FWD_BASIC"], None),
    ("gbuffers_textured",    "program/gbuffers_forward.glsl", V330, {}, ["FWD_TEXTURED"], None),
    ("gbuffers_textured_lit","program/gbuffers_forward.glsl", V330, {}, ["FWD_TEXTURED"], None),
    ("gbuffers_weather",     "program/gbuffers_forward.glsl", V330, {}, ["FWD_WEATHER"], None),
    ("gbuffers_spidereyes",  "program/gbuffers_forward.glsl", V330, {}, ["FWD_EMISSIVE"], None),
    ("gbuffers_beaconbeam",  "program/gbuffers_forward.glsl", V330, {}, ["FWD_EMISSIVE"], None),
    ("gbuffers_armor_glint", "program/gbuffers_forward.glsl", V330, {}, ["FWD_GLINT"], None),
    ("gbuffers_damagedblock","program/gbuffers_forward.glsl", V330, {}, ["FWD_DAMAGED"], None),
    # --- sky, clouds, translucents ---
    ("gbuffers_skybasic",    "program/gbuffers_sky.glsl",    V330, {}, ["SKY_BASIC"], None),
    ("gbuffers_skytextured", "program/gbuffers_sky.glsl",    V330, {}, ["SKY_TEXTURED"], None),
    ("gbuffers_clouds",      "program/clouds.glsl",          V330, {}, [], None),
    ("gbuffers_water",       "program/gbuffers_water.glsl",  V330, {}, ["GBUFFERS_WATER"], None),
    ("gbuffers_hand_water",  "program/gbuffers_water.glsl",  V330, {}, ["GBUFFERS_HAND_WATER"], None),
    # --- deferred passes ---
    ("deferred",             "program/deferred.glsl",        V330, {}, [], None),
    ("deferred1",            "program/deferred1.glsl",       V330, {}, [], None),
    ("deferred2",            "program/denoise_seed.glsl",    V330, {}, [], None),
    ("deferred3",            "program/denoise1.glsl",        V330, {}, [], None),
    ("deferred4",            "program/denoise2.glsl",        V330, {}, [], None),
    ("deferred5",            "program/denoise3.glsl",        V330, {}, [], None),
    ("deferred6",            "program/lighting.glsl",        V330, {}, [], None),
    # --- post-processing ---
    ("composite",            "program/composite.glsl",       V330, {}, [], None),
    ("composite1",           "program/taa_resolve.glsl",     V330, {}, [], None),
    ("composite2",           "program/sharpen.glsl",         V330, {}, [], None),
    ("final",                "program/final.glsl",           V330, {}, [], None),
]

def render(name, source, version, exts, extra, compute, dim):
    files = {}
    for ext, st in ([(".csh", "COMPUTE_SHADER")] if compute else [(".vsh", "VERTEX_SHADER"), (".fsh", "FRAGMENT_SHADER")]):
        body = [f"#version {version}"] + [f"#extension {e}" for e in exts.get(ext[1:], [])] + [""]
        body += [HEADER.rstrip("\n"), f"// Source: shaders/{source}"]
        if compute:
            body.append(f"// {compute[2]}")
        body.append("")
        body += [f"#define {st}", f"#define {dim}"] + [f"#define {d}" for d in extra] + [""]
        if compute:
            body += [compute[0], compute[1], ""]
        body += [f'#include "/{source}"', ""]
        files[name + ext] = "\n".join(body)
    return files

def main():
    check = "--check" in sys.argv
    changed = []
    for world, dim in DIMENSIONS.items():
        os.makedirs(os.path.join(ROOT, world), exist_ok=True)
        for entry in PROGRAMS:
            for fname, text in render(*entry, dim).items():
                path = os.path.join(ROOT, world, fname)
                old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
                if old != text:
                    changed.append(f"{world}/{fname}")
                    if not check:
                        with open(path, "w", encoding="utf-8", newline="\n") as f:
                            f.write(text)
    # Old files that are not in the table (deleted programs)
    known = {n + e for n, *_ in PROGRAMS for e in (".vsh", ".fsh", ".csh")}
    stray = [f"{w}/{f}" for w in DIMENSIONS for f in os.listdir(os.path.join(ROOT, w))
             if f.endswith((".vsh", ".fsh", ".csh")) and f not in known]
    if check:
        if changed or stray:
            for c in changed: print("DIFFERS:", c)
            for s in stray: print("NOT IN TABLE:", s)
            sys.exit(1)
        print(f"wrappers up to date ({len(PROGRAMS)} programs x {len(DIMENSIONS)} dimensions)")
    else:
        print(f"{len(changed)} files written")
        for s in stray: print("WARNING: file not in the table:", s)

if __name__ == "__main__":
    main()
